apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app-demo-container
          image: app_demo:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never  # Usa esto si estás ejecutando localmente y no usas un registry
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
spec:
  selector:
    app: app-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
